before_install:
  - git config --global user.name travis
  - git config --global user.email travis@locahost
language: node_js
script:
  - npm run spec
node_js:
  - '7'
  - '6'
  - '5'
  - '4'
sudo: false
notifications:
  email:
    on_success: always
    on_failure: always
